apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: hana-cloud-hana-ml-car-price-inference-rest-api-test1 # Executable ID (max length 64 lowercase-hyphen-separated), please modify this to any value if you are not the only user of your SAP AI Core instance. Example: `first-pipeline-1234`
  annotations:
    scenarios.ai.sap.com/name: "Hana cloud - Hana ml - Car Price - Test 1"
    scenarios.ai.sap.com/description: "Estimate the price of a use car with SAP Hana cloud - Hana ml-1"
    executables.ai.sap.com/name: "HANACLOUDHANAMLCarPriceInferenceRESTAPI" # No spaces allowed in the name here, let's try with no - also
    executables.ai.sap.com/description: "Create estimate-1"
  labels:
    scenarios.ai.sap.com/id: "hana-cloud-hana-ml-car-price-test1" # The scenario ID to which the serving template belongs
    ai.sap.com/version: "0.0.1"
spec:   
  template:
    apiVersion: "serving.kserve.io/v1beta1" 
    metadata:
       annotations: |
         autoscaling.knative.dev/metric: concurrency   # condition when to scale
         autoscaling.knative.dev/target: 1
         autoscaling.knative.dev/targetBurstCapacity: 0
       labels: |
         ai.sap.com/resourcePlan: starter # computing power
    spec: |
       predictor:
         imagePullSecrets:
         - name: credstutorialrepo-1   # your docker registry secret NAME
         minReplicas: 1
         maxReplicas: 5    # how much to scale
         containers:
         - name: kserve-container
           image: docker.io/diegobovolin/hana-cloud-hana-ml-car-price-restapi-inference:02 # Your docker image name
           ports:
             - containerPort: 9001    # customizable port
               protocol: TCP   
           command: ["/bin/sh", "-c"]
           args:
             - "python /app/src/main.py"
           env:
           - name: HANA_ADDRESS # Name of the environment variable that will be available in the image
             valueFrom:
               secretKeyRef:
                 name: hanacloudcred  # Name of the generic secret created in SAP AI Core for the Resource Group
                 key: address    # Name of the key from the JSON string that is saved as generic secret    
           - name: HANA_PORT 
             valueFrom:
               secretKeyRef:
                 name: hanacloudcred   # same as above
                 key: port    
           - name: HANA_USER 
             valueFrom:
               secretKeyRef:
                 name: hanacloudcred   
                 key: user   
           - name: HANA_PASSWORD 
             valueFrom:
               secretKeyRef:
                 name: hanacloudcred   
                 key: password
